# Generated by Django 5.1.4 on 2026-02-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='context_blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reminder',
            name='generation_prompt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reminder',
            name='offset_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='reminder',
            name='trigger_delay_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='reminder',
            name='trigger_event',
            field=models.CharField(blank=True, choices=[('workout_completed', 'Завершение тренировки')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('morning', 'Утреннее приветствие'), ('meal_program', 'Приём пищи (программа)'), ('meal', 'Приём пищи'), ('water', 'Вода'), ('workout', 'Тренировка'), ('weigh_in', 'Взвешивание'), ('event', 'По событию'), ('custom', 'Другое')], default='custom', max_length=20),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
