# Generated by Django 5.1.4 on 2026-01-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('weight', 'Вес'), ('sleep', 'Сон'), ('steps', 'Шаги'), ('heart_rate', 'Пульс'), ('blood_pressure', 'Давление'), ('water', 'Вода'), ('custom', 'Другое')], max_length=20)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Вручную'), ('photo', 'Фото'), ('fitness_tracker', 'Трекер')], default='manual', max_length=20)),
                ('recorded_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to='accounts.client')),
            ],
            options={
                'db_table': 'health_metrics',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
