# Generated by Django 5.1.4 on 2026-01-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('weight', 'Вес'), ('sleep', 'Сон'), ('steps', 'Шаги'), ('heart_rate', 'Пульс'), ('blood_pressure', 'Давление'), ('water', 'Вода'), ('active_calories', 'Калории активности'), ('custom', 'Другое')], max_length=20),
        ),
    ]
