# Generated by Django 5.1.4 on 2026-01-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_gender_to_client'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['is_active'], name='exercises_is_acti_9a5544_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='exercises_name_26c749_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['-created_at'], name='exercises_created_0e0ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['is_active', '-created_at'], name='exercises_is_acti_37327b_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['is_active', 'name'], name='exercises_is_acti_3784ec_idx'),
        ),
    ]
