# Generated by Django 5.1.4 on 2026-01-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Фёдор', max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('style_description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(default='')),
                ('greeting_message', models.TextField(blank=True)),
                ('ai_provider', models.CharField(default='openai', max_length=20)),
                ('ai_model_chat', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('ai_model_vision', models.CharField(default='gpt-4o', max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_persona', to='accounts.coach')),
            ],
            options={
                'db_table': 'bot_personas',
            },
        ),
    ]
