# Generated by Django 5.1.4 on 2026-01-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_telegram_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
