# Generated by Django 5.1.4 on 2026-01-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_botpersona_food_response_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
