# Generated by Django 5.1.4 on 2026-01-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_telegrambot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='miniapp_short_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
