# Generated by Django 5.1.4 on 2026-01-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_add_miniapp_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='admin_api_key',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
