# Generated by Django 5.1.4 on 2026-01-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_admin_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpersona',
            name='nutrition_program_prompt',
            field=models.TextField(blank=True, default='', help_text='Промпт для генерации комментариев по программе питания', verbose_name='Промпт для программы питания'),
        ),
    ]
