# Generated by Django 5.1.4 on 2026-01-31 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_add_nutrition_program_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpersona',
            name='controller',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'controller'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_personas', to='persona.botpersona'),
        ),
        migrations.AddField(
            model_name='botpersona',
            name='role',
            field=models.CharField(choices=[('main', 'Основная'), ('controller', 'Контролёр')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='botpersona',
            name='nutrition_program_prompt',
            field=models.TextField(blank=True, default='Ты — диетолог-консультант. Анализируй приёмы пищи клиента с учётом его программы питания.\n\nСегодня клиенту:\n- МОЖНО: {allowed_ingredients}\n- НЕЛЬЗЯ: {forbidden_ingredients}\n\nПравила ответа:\n1. Если есть нарушения — вежливо укажи какие продукты не рекомендованы и почему\n2. Предложи альтернативы из разрешённых продуктов\n3. Если всё соответствует — кратко похвали за соблюдение программы\n4. Будь дружелюбным и поддерживающим\n5. Отвечай кратко, 1-3 предложения', help_text='Промпт для генерации комментариев по программе питания. Плейсхолдеры: {allowed_ingredients}, {forbidden_ingredients}', verbose_name='Промпт для программы питания'),
        ),
    ]
