# Generated by Django 5.1.4 on 2026-01-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0012_add_role_and_controller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botpersona',
            name='nutrition_program_prompt',
            field=models.TextField(blank=True, default='', help_text='Промпт для контролёра программы питания. Переменные: {program_info}, {program_history}, {planned_meal}, {actual_meal}, {next_meal}', verbose_name='Промпт для программы питания'),
        ),
    ]
