# Generated by Django 5.1.4 on 2026-01-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0013_alter_botpersona_nutrition_program_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpersona',
            name='shopping_list_prompt',
            field=models.TextField(blank=True, default='', help_text='Промпт для генерации списка покупок. Переменные: {meals_description}', verbose_name='Промпт для списка покупок'),
        ),
    ]
