# Generated by Django 5.1.4 on 2026-01-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='telegram_bot_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coach',
            name='telegram_notification_chat_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
