# Generated by Django 5.1.4 on 2026-01-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_gender_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activity_level',
            field=models.CharField(blank=True, choices=[('sedentary', 'Сидячий'), ('light', 'Лёгкая активность'), ('moderate', 'Умеренная активность'), ('active', 'Высокая активность'), ('very_active', 'Очень высокая активность')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
