# Generated by Django 5.1.4 on 2026-01-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_age_and_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='meal_analysis_mode',
            field=models.CharField(choices=[('ask', 'Спрашивать'), ('fast', 'Быстрый'), ('smart', 'Умный')], default='ask', max_length=10),
        ),
    ]
