# Generated by Django 5.1.4 on 2026-02-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_meal_analysis_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='memory',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='client',
            name='pending_memory',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
