# Generated by Django 5.1.4 on 2026-01-31 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_meal_analysis_mode'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuaweiHealthConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField()),
                ('token_expires_at', models.DateTimeField()),
                ('scopes', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='huawei_health_connection', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Huawei Health Connection',
                'verbose_name_plural': 'Huawei Health Connections',
                'db_table': 'huawei_health_connections',
            },
        ),
        migrations.CreateModel(
            name='HuaweiHealthSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='running', max_length=20)),
                ('metrics_synced', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.huaweihealthconnection')),
            ],
            options={
                'verbose_name': 'Huawei Health Sync Log',
                'verbose_name_plural': 'Huawei Health Sync Logs',
                'db_table': 'huawei_health_sync_logs',
                'ordering': ['-started_at'],
            },
        ),
    ]
