# Generated by Django 5.1.4 on 2026-01-24 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=uuid.uuid4, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(default=1)),
                ('uses_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='accounts.coach')),
            ],
            options={
                'db_table': 'invite_links',
            },
        ),
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('choice', 'Выбор'), ('multi_choice', 'Множественный выбор'), ('date', 'Дата')], max_length=15)),
                ('options', models.JSONField(blank=True, default=list)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('field_key', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_questions', to='accounts.coach')),
            ],
            options={
                'db_table': 'onboarding_questions',
                'ordering': ['order'],
            },
        ),
    ]
