# Generated by Django 5.1.4 on 2026-01-24 23:26

import apps.onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='code',
            field=models.CharField(default=apps.onboarding.models._generate_invite_code, max_length=32, unique=True),
        ),
    ]
