# Generated by Django 5.1.4 on 2026-01-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='meals/%Y/%m/%d/')),
                ('image_type', models.CharField(choices=[('food', 'Еда'), ('data', 'Цифровые данные'), ('other', 'Прочее')], default='food', max_length=10)),
                ('dish_name', models.CharField(max_length=200)),
                ('dish_type', models.CharField(blank=True, max_length=50)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('proteins', models.FloatField(blank=True, null=True)),
                ('fats', models.FloatField(blank=True, null=True)),
                ('carbohydrates', models.FloatField(blank=True, null=True)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('health_analysis', models.JSONField(blank=True, default=dict)),
                ('ai_confidence', models.IntegerField(blank=True, null=True)),
                ('plate_type', models.CharField(blank=True, max_length=100)),
                ('layout', models.CharField(blank=True, max_length=200)),
                ('decorations', models.CharField(blank=True, max_length=200)),
                ('meal_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='accounts.client')),
            ],
            options={
                'db_table': 'meals',
                'ordering': ['-meal_time'],
            },
        ),
    ]
