# Generated by Django 5.1.4 on 2026-01-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='meals/thumbnails/%Y/%m/%d/'),
        ),
    ]
