# Generated by Django 5.1.4 on 2026-01-28 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_age_and_activity_level'),
        ('meals', '0002_add_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, upload_to='meal_drafts/%Y/%m/%d/')),
                ('dish_name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('dish_type', models.CharField(blank=True, max_length=50, verbose_name='Тип приёма пищи')),
                ('estimated_weight', models.IntegerField(default=0, verbose_name='Оценка веса (г)')),
                ('ai_confidence', models.FloatField(default=0.0, verbose_name='Уверенность AI (0-1)')),
                ('ingredients', models.JSONField(default=list, verbose_name='Ингредиенты')),
                ('calories', models.FloatField(default=0, verbose_name='Калории')),
                ('proteins', models.FloatField(default=0, verbose_name='Белки')),
                ('fats', models.FloatField(default=0, verbose_name='Жиры')),
                ('carbohydrates', models.FloatField(default=0, verbose_name='Углеводы')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждён'), ('cancelled', 'Отменён')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_drafts', to='accounts.client')),
                ('meal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft', to='meals.meal')),
            ],
            options={
                'verbose_name': 'Черновик приёма пищи',
                'verbose_name_plural': 'Черновики приёмов пищи',
                'db_table': 'meal_drafts',
                'ordering': ['-created_at'],
            },
        ),
    ]
