# Generated by Django 5.1.4 on 2026-01-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_add_meal_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ai_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий AI'),
        ),
    ]
