# Generated by Django 5.1.4 on 2026-01-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_add_ai_comment_to_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='program_check_status',
            field=models.CharField(blank=True, choices=[('compliant', 'Соответствует'), ('violation', 'Нарушение')], max_length=20, null=True, verbose_name='Статус проверки программы'),
        ),
    ]
