# Generated by Django 5.1.4 on 2026-02-01 09:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_meal_analysis_mode'),
        ('meals', '0005_add_program_check_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тега')),
                ('color', models.CharField(default='#3B82F6', help_text='HEX-код цвета для отображения (например, #3B82F6)', max_length=7, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dish_tags', to='accounts.coach', verbose_name='Коуч')),
            ],
            options={
                'verbose_name': 'Тег блюда',
                'verbose_name_plural': 'Теги блюд',
                'db_table': 'dish_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, help_text='Краткое описание блюда', verbose_name='Описание')),
                ('recipe', models.TextField(blank=True, help_text='Пошаговый рецепт приготовления (поддерживает Markdown)', verbose_name='Рецепт')),
                ('portion_weight', models.PositiveIntegerField(default=0, verbose_name='Вес порции (г)')),
                ('calories', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Калории')),
                ('proteins', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Белки')),
                ('fats', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Жиры')),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Углеводы')),
                ('cooking_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='Время приготовления (мин)')),
                ('photo', models.ImageField(blank=True, upload_to='dishes/%Y/%m/', verbose_name='Фото блюда')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на видео-рецепт (YouTube, etc.)', verbose_name='Ссылка на видео')),
                ('ingredients', models.JSONField(blank=True, default=list, help_text='Список ингредиентов: [{product_id, name, weight, calories, proteins, fats, carbohydrates}]', verbose_name='Ингредиенты')),
                ('shopping_links', models.JSONField(blank=True, default=list, help_text='Ссылки на магазины: [{title, url}]', verbose_name='Ссылки на покупку')),
                ('meal_types', models.JSONField(blank=True, default=list, help_text='Для каких приёмов пищи подходит: ["breakfast", "lunch", ...]', verbose_name='Типы приёмов пищи')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные блюда не отображаются в списке', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='accounts.coach', verbose_name='Коуч')),
                ('tags', models.ManyToManyField(blank=True, related_name='dishes', to='meals.dishtag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
                'db_table': 'dishes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('calories_per_100g', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Калории на 100г')),
                ('proteins_per_100g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Белки на 100г')),
                ('fats_per_100g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Жиры на 100г')),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Углеводы на 100г')),
                ('category', models.CharField(choices=[('dairy', 'Молочные продукты'), ('meat', 'Мясо'), ('fish', 'Рыба и морепродукты'), ('vegetables', 'Овощи'), ('fruits', 'Фрукты'), ('grains', 'Крупы и злаки'), ('nuts', 'Орехи и семена'), ('oils', 'Масла и жиры'), ('spices', 'Специи и приправы'), ('other', 'Прочее')], default='other', max_length=50, verbose_name='Категория')),
                ('is_verified', models.BooleanField(default=False, help_text='Подтверждено коучем после AI-подсказки', verbose_name='Проверено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.coach', verbose_name='Коуч')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='dishtag',
            index=models.Index(fields=['coach'], name='dish_tags_coach_i_809e73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dishtag',
            unique_together={('coach', 'name')},
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['coach', 'name'], name='dishes_coach_i_62f054_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['coach', 'is_active'], name='dishes_coach_i_ad9aec_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['-updated_at'], name='dishes_updated_f02124_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['coach', 'name'], name='products_coach_i_ca7d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_fce6e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('coach', 'name')},
        ),
    ]
