# Generated by Django 5.1.4 on 2026-02-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0006_add_product_dishtag_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Автоматически генерируется из фото (300x300)', upload_to='dishes/thumbnails/%Y/%m/', verbose_name='Миниатюра'),
        ),
    ]
