# Generated by Django 5.1.4 on 2026-01-24 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('content', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/%Y/%m/')),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.coach')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-period_end'],
            },
        ),
    ]
