# Generated by Django 5.1.4 on 2026-01-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_meal_analysis_mode'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('client', 'report_type', 'period_start'), name='unique_client_report_per_period'),
        ),
    ]
