from django.urls import path
from .views import (
    BotPersonaView,
    BotPersonaSetDefaultView,
    AISettingsView,
    AIProviderListView,
    AIProviderDeleteView,
    AIProviderModelsView,
    AIProviderAdminKeyView,
    AIModelListView,
    AIModelDeleteView,
    AIUsageView,
    AITestView,
    TelegramSettingsView,
    TelegramTestView,
    DashboardStatsView,
    OpenAIUsageView,
)

urlpatterns = [
    path('', BotPersonaView.as_view(), name='bot_persona'),
    path('<int:pk>/set_default/', BotPersonaSetDefaultView.as_view(), name='bot_persona_set_default'),
    path('ai/', AISettingsView.as_view(), name='ai_settings'),
    path('providers/', AIProviderListView.as_view(), name='ai_providers'),
    path('providers/<int:pk>/', AIProviderDeleteView.as_view(), name='ai_provider_delete'),
    path('providers/<int:pk>/admin-key/', AIProviderAdminKeyView.as_view(), name='ai_provider_admin_key'),
    path('providers/models/', AIProviderModelsView.as_view(), name='ai_provider_models'),
    path('models/', AIModelListView.as_view(), name='ai_models'),
    path('models/<int:pk>/', AIModelDeleteView.as_view(), name='ai_model_delete'),
    path('ai/usage/', AIUsageView.as_view(), name='ai_usage'),
    path('ai/usage/openai/', OpenAIUsageView.as_view(), name='openai_usage'),
    path('ai/test/', AITestView.as_view(), name='ai_test'),
    path('telegram/', TelegramSettingsView.as_view(), name='telegram_settings'),
    path('telegram/test/', TelegramTestView.as_view(), name='telegram_test'),
    path('dashboard/', DashboardStatsView.as_view(), name='dashboard_stats'),
]
