# Generated by Django 5.1.4 on 2026-01-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_interactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_by_coach',
            field=models.BooleanField(default=False),
        ),
    ]
