# Generated by Django 5.1.4 on 2026-01-25 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_client_manual_mode'),
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('skipped', 'Пропущена')], default='draft', max_length=15)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Примерная длительность в минутах', null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='intermediate', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Заметки коуча для клиента')),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=60, help_text='За сколько минут напомнить')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='accounts.client')),
            ],
            options={
                'db_table': 'client_workouts',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_weeks', models.PositiveIntegerField(default=4)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('completed', 'Завершена'), ('paused', 'Приостановлена')], default='draft', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('current_week', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_programs', to='accounts.client')),
            ],
            options={
                'db_table': 'training_programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block_type', models.CharField(choices=[('warmup', 'Разминка'), ('main', 'Основная часть'), ('cooldown', 'Заминка'), ('custom', 'Пользовательский')], default='main', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rounds', models.PositiveIntegerField(default=1)),
                ('rest_between_rounds', models.PositiveIntegerField(default=60, help_text='Отдых между раундами в секундах')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workouts.clientworkout')),
            ],
            options={
                'db_table': 'workout_blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parameters', models.JSONField(default=dict)),
                ('rest_after', models.PositiveIntegerField(default=60, help_text='Отдых после упражнения в секундах')),
                ('notes', models.TextField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workoutblock')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_usages', to='exercises.exercise')),
            ],
            options={
                'db_table': 'workout_exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершена'), ('paused', 'Приостановлена'), ('abandoned', 'Прервана')], default='in_progress', max_length=15)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('total_exercises', models.PositiveIntegerField(default=0)),
                ('completed_exercises', models.PositiveIntegerField(default=0)),
                ('total_sets', models.PositiveIntegerField(default=0)),
                ('completed_sets', models.PositiveIntegerField(default=0)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('client_notes', models.TextField(blank=True)),
                ('client_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fatigue_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='workouts.clientworkout')),
            ],
            options={
                'db_table': 'workout_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('actual_parameters', models.JSONField(default=dict)),
                ('planned_parameters', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workouts.workoutexercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_logs', to='workouts.workoutsession')),
            ],
            options={
                'db_table': 'exercise_logs',
                'ordering': ['workout_exercise__order', 'set_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSuperset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rounds', models.PositiveIntegerField(default=1)),
                ('rest_after', models.PositiveIntegerField(default=90, help_text='Отдых после суперсета в секундах')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supersets', to='workouts.workoutblock')),
            ],
            options={
                'db_table': 'workout_supersets',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='superset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='workouts.workoutsuperset'),
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('estimated_duration', models.PositiveIntegerField(blank=True, help_text='Примерная длительность в минутах', null=True)),
                ('difficulty', models.CharField(choices=[('beginner', 'Начинающий'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='intermediate', max_length=15)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to='accounts.coach')),
            ],
            options={
                'db_table': 'workout_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('days_of_week', models.JSONField(default=list, help_text='Список дней недели [0, 2, 4] = Пн, Ср, Пт')),
                ('time', models.TimeField(help_text='Время тренировки')),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_schedules', to='accounts.client')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='workouts.workouttemplate')),
            ],
            options={
                'db_table': 'training_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='clientworkout',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_workouts', to='workouts.workouttemplate'),
        ),
        migrations.CreateModel(
            name='WorkoutTemplateBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('block_type', models.CharField(choices=[('warmup', 'Разминка'), ('main', 'Основная часть'), ('cooldown', 'Заминка'), ('custom', 'Пользовательский')], default='main', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('rounds', models.PositiveIntegerField(default=1)),
                ('rest_between_rounds', models.PositiveIntegerField(default=60, help_text='Отдых между раундами в секундах')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='workouts.workouttemplate')),
            ],
            options={
                'db_table': 'workout_template_blocks',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('parameters', models.JSONField(default=dict)),
                ('rest_after', models.PositiveIntegerField(default=60)),
                ('superset_group', models.PositiveIntegerField(blank=True, help_text='Упражнения с одинаковым номером выполняются как суперсет', null=True)),
                ('notes', models.TextField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workouttemplateblock')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_usages', to='exercises.exercise')),
            ],
            options={
                'db_table': 'workout_template_exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramWorkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('day_of_week', models.PositiveIntegerField(help_text='День недели: 0=Пн, 1=Вт, ..., 6=Вс')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_entries', to='workouts.clientworkout')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_workouts', to='workouts.trainingprogram')),
            ],
            options={
                'db_table': 'program_workouts',
                'ordering': ['week_number', 'day_of_week'],
                'unique_together': {('program', 'week_number', 'day_of_week')},
            },
        ),
    ]
