# Generated by Django 5.1.4 on 2026-01-27 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_gender_to_client'),
        ('workouts', '0002_fitdb_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttemplate',
            name='created_for_client',
            field=models.ForeignKey(blank=True, help_text='Клиент, для которого создана эта тренировка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personalized_workouts', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='is_personalized',
            field=models.BooleanField(default=False, help_text='True если это персонализированная копия для клиента'),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='source_template',
            field=models.ForeignKey(blank=True, help_text='Шаблон, из которого была создана эта тренировка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_workouts', to='workouts.workouttemplate'),
        ),
    ]
