# Generated by Django 5.1.4 on 2026-01-27 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
        ('workouts', '0003_personalized_workouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitDBActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('workout_started', 'Тренировка начата'), ('workout_paused', 'Тренировка приостановлена'), ('workout_resumed', 'Тренировка возобновлена'), ('workout_completed', 'Тренировка завершена'), ('exercise_started', 'Упражнение начато'), ('exercise_completed', 'Упражнение завершено'), ('exercise_skipped', 'Упражнение пропущено'), ('set_completed', 'Подход выполнен'), ('set_skipped', 'Подход пропущен'), ('rest_started', 'Отдых начат'), ('rest_skipped', 'Отдых пропущен')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('set_number', models.PositiveIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='exercises.exercise')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='workouts.fitdbworkoutsession')),
            ],
            options={
                'db_table': 'fitdb_activity_logs',
                'ordering': ['session', 'timestamp'],
            },
        ),
    ]
