# Generated by Django 5.1.4 on 2026-01-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_gender_to_client'),
        ('workouts', '0004_add_activity_log'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fitdbworkoutassignment',
            index=models.Index(fields=['client', '-assigned_at'], name='fitdb_worko_client__e23313_idx'),
        ),
        migrations.AddIndex(
            model_name='fitdbworkoutassignment',
            index=models.Index(fields=['client', 'status'], name='fitdb_worko_client__74541d_idx'),
        ),
        migrations.AddIndex(
            model_name='fitdbworkoutassignment',
            index=models.Index(fields=['workout'], name='fitdb_worko_workout_74566a_idx'),
        ),
        migrations.AddIndex(
            model_name='fitdbworkoutassignment',
            index=models.Index(fields=['status'], name='fitdb_worko_status_0398ff_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttemplate',
            index=models.Index(fields=['is_active'], name='workout_tem_is_acti_85e7ca_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttemplate',
            index=models.Index(fields=['-created_at'], name='workout_tem_created_64f05c_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttemplate',
            index=models.Index(fields=['is_active', '-created_at'], name='workout_tem_is_acti_24d7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='workouttemplate',
            index=models.Index(fields=['coach', 'is_active'], name='workout_tem_coach_i_54d8ff_idx'),
        ),
    ]
