# Generated by Django 5.1.4 on 2026-01-30 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_meal_analysis_mode'),
        ('workouts', '0005_fitdbworkoutassignment_fitdb_worko_client__e23313_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitdbworkoutsession',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to='accounts.client'),
        ),
    ]
