# Generated by Django 5.1.4 on 2026-02-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_add_client_to_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitdbexerciselog',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
