# Generated by Django 5.1.4 on 2026-02-08 07:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_add_duration_to_exercise_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitdbactivitylog',
            name='event_type',
            field=models.CharField(choices=[('workout_started', 'Тренировка начата'), ('workout_paused', 'Тренировка приостановлена'), ('workout_resumed', 'Тренировка возобновлена'), ('workout_completed', 'Тренировка завершена'), ('exercise_started', 'Упражнение начато'), ('exercise_completed', 'Упражнение завершено'), ('exercise_skipped', 'Упражнение пропущено'), ('set_started', 'Подход начат'), ('set_completed', 'Подход выполнен'), ('set_skipped', 'Подход пропущен'), ('rest_started', 'Отдых начат'), ('rest_skipped', 'Отдых пропущен')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fitdbworkoutsession',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
