# Generated by Django 5.1.4 on 2026-02-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_session_started_at_default_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitdbworkoutsession',
            name='completion_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
