# Generated by Django 5.1.4 on 2026-01-31 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_add_meal_analysis_mode'),
        ('meals', '0004_add_ai_comment_to_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Продолжительность (дней)')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_programs', to='accounts.client', verbose_name='Клиент')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_programs', to='accounts.coach', verbose_name='Коуч')),
            ],
            options={
                'verbose_name': 'Программа питания',
                'verbose_name_plural': 'Программы питания',
                'db_table': 'nutrition_programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(verbose_name='Номер дня')),
                ('date', models.DateField(verbose_name='Дата')),
                ('allowed_ingredients', models.JSONField(blank=True, default=list, help_text='Список разрешённых ингредиентов [{"name": "яблоко"}, ...]', verbose_name='Разрешённые ингредиенты')),
                ('forbidden_ingredients', models.JSONField(blank=True, default=list, help_text='Список запрещённых ингредиентов [{"name": "сахар"}, ...]', verbose_name='Запрещённые ингредиенты')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки коуча')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='nutrition_programs.nutritionprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'День программы питания',
                'verbose_name_plural': 'Дни программы питания',
                'db_table': 'nutrition_program_days',
                'ordering': ['program', 'day_number'],
                'unique_together': {('program', 'day_number')},
            },
        ),
        migrations.CreateModel(
            name='MealComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compliant', models.BooleanField(verbose_name='Соответствует программе')),
                ('found_forbidden', models.JSONField(blank=True, default=list, help_text='Список найденных запрещённых ингредиентов', verbose_name='Найденные запрещённые ингредиенты')),
                ('found_allowed', models.JSONField(blank=True, default=list, help_text='Список найденных разрешённых ингредиентов', verbose_name='Найденные разрешённые ингредиенты')),
                ('ai_comment', models.TextField(blank=True, help_text='Комментарий AI с рекомендациями', verbose_name='Комментарий AI')),
                ('coach_notified', models.BooleanField(default=False, verbose_name='Коуч уведомлён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='meals.meal', verbose_name='Приём пищи')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_checks', to='nutrition_programs.nutritionprogramday', verbose_name='День программы')),
            ],
            options={
                'verbose_name': 'Проверка соответствия',
                'verbose_name_plural': 'Проверки соответствия',
                'db_table': 'meal_compliance_checks',
                'ordering': ['-created_at'],
            },
        ),
    ]
