# Generated by Django 5.1.4 on 2026-01-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_meal_analysis_mode'),
        ('meals', '0005_add_program_check_status'),
        ('nutrition_programs', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='mealcompliancecheck',
            index=models.Index(fields=['program_day', 'is_compliant'], name='meal_compli_program_41c76b_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionprogram',
            index=models.Index(fields=['client', 'status'], name='nutrition_p_client__27e6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionprogram',
            index=models.Index(fields=['client', 'start_date', 'end_date'], name='nutrition_p_client__817387_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionprogram',
            index=models.Index(fields=['coach', 'status'], name='nutrition_p_coach_i_9ebc25_idx'),
        ),
        migrations.AddIndex(
            model_name='nutritionprogramday',
            index=models.Index(fields=['program', 'date'], name='nutrition_p_program_df7ca2_idx'),
        ),
    ]
