# Generated by Django 5.1.4 on 2026-01-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_programs', '0002_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionprogram',
            name='general_notes',
            field=models.TextField(blank=True, help_text='Заметки на всю программу (про воду, режим сна, кофе и т.д.)', verbose_name='Общие заметки'),
        ),
        migrations.AddField(
            model_name='nutritionprogramday',
            name='activity',
            field=models.TextField(blank=True, help_text='Рекомендации по физической активности на день', verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='nutritionprogramday',
            name='meals',
            field=models.JSONField(blank=True, default=list, help_text='Список приёмов пищи [{"type": "breakfast", "time": "8:00", "name": "Завтрак", "description": "..."}]', verbose_name='Приёмы пищи'),
        ),
        migrations.CreateModel(
            name='MealReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('snack1', 'Перекус 1'), ('lunch', 'Обед'), ('snack2', 'Перекус 2'), ('dinner', 'Ужин')], max_length=20, verbose_name='Тип приёма пищи')),
                ('meal_time', models.CharField(blank=True, help_text='Время из программы (8:00, 14:00...)', max_length=10, verbose_name='Время приёма пищи')),
                ('photo_file_id', models.CharField(blank=True, max_length=255, verbose_name='Telegram file_id фото')),
                ('photo_url', models.URLField(blank=True, help_text='URL фото если хранится в S3 или другом хранилище', verbose_name='URL фото')),
                ('planned_description', models.TextField(blank=True, help_text='Описание блюда из программы питания', verbose_name='Запланированное блюдо')),
                ('recognized_ingredients', models.JSONField(blank=True, default=list, help_text='Ингредиенты, распознанные AI на фото', verbose_name='Распознанные ингредиенты')),
                ('is_compliant', models.BooleanField(default=True, verbose_name='Соответствует программе')),
                ('compliance_score', models.PositiveIntegerField(default=100, help_text='Процент соответствия запланированному блюду (0-100)', verbose_name='Оценка соответствия (%)')),
                ('ai_analysis', models.TextField(blank=True, help_text='Подробный анализ: что совпало, что отличается', verbose_name='Анализ AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_reports', to='nutrition_programs.nutritionprogramday', verbose_name='День программы')),
            ],
            options={
                'verbose_name': 'Фото-отчёт приёма пищи',
                'verbose_name_plural': 'Фото-отчёты приёмов пищи',
                'db_table': 'meal_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['program_day', 'meal_type'], name='meal_report_program_0704cb_idx'), models.Index(fields=['program_day', 'created_at'], name='meal_report_program_76dc73_idx')],
            },
        ),
    ]
