# Generated by Django 5.1.4 on 2026-01-31 13:37

import apps.nutrition_programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_programs', '0003_add_meals_and_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealreport',
            name='photo_url',
            field=models.TextField(blank=True, help_text='URL фото (S3) или data URL (base64)', verbose_name='URL или data URL фото'),
        ),
        migrations.AlterField(
            model_name='nutritionprogramday',
            name='meals',
            field=models.JSONField(blank=True, default=list, help_text='Список приёмов пищи [{"type": "breakfast", "time": "8:00", "name": "Завтрак", "description": "..."}]', validators=[apps.nutrition_programs.models.validate_meals_structure], verbose_name='Приёмы пищи'),
        ),
    ]
