# Generated by Django 5.1.4 on 2026-01-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition_programs', '0004_change_photo_url_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionprogramday',
            name='shopping_list',
            field=models.JSONField(blank=True, default=list, help_text='Список продуктов для покупки [{"name": "Молоко", "category": "dairy"}, ...]', verbose_name='Список покупок'),
        ),
    ]
